rplidar_node:
  ros__parameters:
    channel_type: "serial"
    serial_port: "/dev/ttyUSB1"
    serial_baudrate: 460800
    frame_id: "laser"
    inverted: false
    angle_compensate: true
    scan_mode: "Standard"
