#ifndef COMMANDS_H
#define COMMANDS_H

#include <stdint.h>

enum class Command : uint8_t {
    PING,
    READ_SUCCESS,
    READ_FAILURE,
    SYNC_TIME,

    START,
    STOP,
    RESET,
    STOP_ALL_BROADCAST,
    RESTORE_ALL_BROADCAST,

    SET_MOTOR_DATA,
    GET_MOTOR_DATA,
    SET_CONTROLLER_PROPERTIES,
    GET_CONTROLLER_PROPERTIES,

    SET_PID_CONSTANTS,
    SET_WHEEL_SETPOINT,

    SET_MOTOR_CONTROL_MODES,
    SET_ODO_BROADCAST_STATUS,
    SEND_ODOMETRY
};

#endif // COMMANDS_H
